// SPDX-License-Identifier: Apache-2.0
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

const read = (path) => readFile(new URL(path, import.meta.url), 'utf8');

test('business routes do not import mock implementation details', async () => {
  const [server, domain, outbox] = await Promise.all([
    read('../src/server.mjs'),
    read('../src/domain.mjs'),
    read('../src/outbox.mjs'),
  ]);
  assert.equal(domain.includes('mock-agent-work-adapter'), false);
  assert.equal(outbox.includes('mock-agent-work-adapter'), false);
  assert.equal(server.includes('MockAgentWorkAdapter'), true);
  assert.equal(server.includes('OpenAICompatibleAgentWorkAdapter'), true);
  assert.equal(server.includes('AgentWorkRouter'), true);
});

test('mock namespace, business-owned versions, and UI remain explicitly bounded', async () => {
  const [adapter, migration, projectsMigration, html] = await Promise.all([
    read('../src/mock-agent-work-adapter.mjs'),
    read('../migrations/001_initial.sql'),
    read('../migrations/003_course_projects.sql'),
    read('../web/index.html'),
  ]);
  assert.match(adapter, /simulated/u);
  assert.match(adapter, /Not Kungfu evidence/u);
  assert.match(migration, /mock_agent_work/u);
  assert.match(projectsMigration, /course_outline_versions/u);
  assert.match(projectsMigration, /FORCE ROW LEVEL SECURITY/u);
  assert.match(html, /backend-banner/u);
  assert.equal(adapter.includes('sha256:'), false);
});

test('qualification faults are explicit and absent without a run id', async () => {
  const { createQualificationFaults } = await import('../src/qualification-faults.mjs');
  const hooks = createQualificationFaults({
    qualificationRunId: '',
    outboxProcessingStaleSeconds: 30,
  });
  assert.equal(hooks.processingStaleSeconds, 30);
  assert.equal(hooks.beforeExecute, undefined);
  assert.equal(hooks.afterExecute, undefined);
});

test('course UI keeps event objects out of messages and only disables workspace controls', async () => {
  const browser = await read('../web/app.js');
  assert.match(browser, /addEventListener\('click', \(\) => showNewCourse\(\)\)/u);
  assert.match(browser, /app\.querySelectorAll\('button, textarea'\)/u);
  assert.equal(browser.includes("addEventListener('click', showNewCourse)"), false);
  assert.equal(browser.includes("document.querySelectorAll('button, textarea')"), false);
});

test('course UI makes Agent contribution and work handoff visible', async () => {
  const browser = await read('../web/app.js');
  assert.match(browser, /Work handoff/u);
  assert.match(browser, /Generated by local AI/u);
  assert.match(browser, /escapeHtml\(agentLabel\)/u);
  assert.match(browser, /courseAgentLabel/u);
  assert.match(browser, /What the Agent changed/u);
  assert.match(browser, /version\.agentRun\?\.action/u);
  assert.match(browser, /Immutable version/u);
  assert.match(browser, /predates structured per-change reporting/u);
  assert.match(browser, /Your brief — not AI-generated/u);
  assert.match(browser, /LOCAL AI OUTPUT STARTS HERE/u);
  assert.match(browser, /MOCK TEMPLATE OUTPUT STARTS HERE/u);
  assert.match(browser, /Everything below was returned by/u);
  assert.match(browser, /not system-prefilled copy/u);
});

test('course UI accepts placeholder examples with Tab and explains staged actions', async () => {
  const [browser, styles] = await Promise.all([
    read('../web/app.js'),
    read('../web/style.css'),
  ]);
  const tabHandler = browser.slice(
    browser.indexOf('function wireTabPlaceholderAcceptance'),
    browser.indexOf('function updateWorkflowProgress'),
  );
  assert.match(browser, /wireTabPlaceholderAcceptance/u);
  assert.match(browser, /event\.key !== 'Tab'/u);
  assert.match(browser, /field\.value = field\.placeholder/u);
  assert.equal(tabHandler.includes('preventDefault'), false);
  assert.match(browser, /runVisibleWorkflow/u);
  assert.match(browser, /hidden model reasoning/u);
  assert.match(browser, /backendState/u);
  assert.match(browser, /Approving version/u);
  assert.match(browser, /Improving your course outline/u);
  assert.match(browser, /newest\.id === previousNewestId/u);
  assert.match(browser, /did not return a new outline/u);
  assert.match(browser, /task: async \(\) => \{[\s\S]*?const newest = result\.course\?\.versions\?\.\[0\]/u);
  assert.match(styles, /workflowStageIn/u);
  assert.match(styles, /workflowStageOut/u);
  assert.match(styles, /prefers-reduced-motion/u);
});

test('runtime polling updates stable menu nodes without replaying the open animation', async () => {
  const [browser, styles] = await Promise.all([
    read('../web/app.js'),
    read('../web/style.css'),
  ]);
  const renderer = browser.slice(
    browser.indexOf('function renderRuntimeMenu'),
    browser.indexOf('async function refreshRuntime'),
  );
  assert.match(browser, /runtimeMenu\.dataset\.initialized/u);
  assert.match(renderer, /textContent =/u);
  assert.match(renderer, /classList\.toggle\('open'/u);
  assert.equal(renderer.includes('runtimeMenu.innerHTML'), false);
  assert.equal(styles.includes('runtimeMenuIn'), false);
});

test('course UI exposes persistent backend binding and unmistakable local AI output', async () => {
  const [browser, styles, domain] = await Promise.all([
    read('../web/app.js'),
    read('../web/style.css'),
    read('../src/domain.mjs'),
  ]);
  assert.match(domain, /h\.backend_kind/u);
  assert.match(domain, /backendKind: project\.backend_kind/u);
  assert.match(browser, /Local AI course/u);
  assert.match(browser, /Local AI generated · Qwen3 0\.6B/u);
  assert.match(browser, /complete course draft below was generated by the local model/u);
  assert.match(browser, /deterministic simulation—not the local model/u);
  assert.match(browser, /Current course model/u);
  assert.match(browser, /Only future versions change/u);
  assert.match(browser, /data-bind-course-backend/u);
  assert.match(browser, /updateSelectedRuntimePanels/u);
  assert.match(browser, /data-selected-runtime-panel="dashboard"/u);
  assert.match(styles, /\.ai-output-hero\.local/u);
  assert.match(styles, /\.ai-generated-content\.local/u);
  assert.match(styles, /\.saved-input-source/u);
  assert.match(styles, /\.output-boundary\.local/u);
  assert.match(styles, /\.generated-section-badge/u);
});

test('course backend switches preserve command routing and historical provenance', async () => {
  const [migration, domain, outbox, server, browser] = await Promise.all([
    read('../migrations/005_course_backend_switches.sql'),
    read('../src/domain.mjs'),
    read('../src/outbox.mjs'),
    read('../src/server.mjs'),
    read('../web/app.js'),
  ]);
  assert.match(migration, /course_backend_switches/u);
  assert.match(migration, /backend_binding_id/u);
  assert.match(migration, /FORCE ROW LEVEL SECURITY/u);
  assert.match(domain, /switchCourseBackend/u);
  assert.match(domain, /state IN \('pending','processing'\)/u);
  assert.match(domain, /backend_kind, backend_binding_id/u);
  assert.match(domain, /type === 'revise_outline'/u);
  assert.match(outbox, /WHERE id = \$1 AND backend_kind = \$5/u);
  assert.match(outbox, /provision_command_id/u);
  assert.match(server, /courseBackendMatch/u);
  assert.match(browser, /versionRuntime/u);
  assert.match(browser, /Selected version backend/u);
  assert.match(browser, /saved version keeps its original model source/u);
});

test('failed inference remains recoverable without weakening provision failures', async () => {
  const [outbox, recoveryLogic, recovery, domain, browser, styles] = await Promise.all([
    read('../src/outbox.mjs'),
    read('../src/outbox-recovery.mjs'),
    read('../migrations/006_recover_failed_inference_actions.sql'),
    read('../src/domain.mjs'),
    read('../web/app.js'),
    read('../web/style.css'),
  ]);
  assert.match(outbox, /projectedStatusAfterDeliveryFailure/u);
  assert.match(recoveryLogic, /commandType === 'provision'/u);
  assert.match(recoveryLogic, /\['generate_outline', 'revise_outline'\]/u);
  assert.match(recovery, /latest command failed during generation\/revision/u);
  assert.match(recovery, /backend_binding_id IS NOT NULL/u);
  assert.match(recovery, /command_type IN \('generate_outline', 'revise_outline'\)/u);
  assert.match(domain, /lastOperationFailure/u);
  assert.match(browser, /The course is safe and ready to continue/u);
  assert.match(browser, /retry or switch models/u);
  assert.match(styles, /\.operation-failure/u);
});

test('long inference delivery is bounded and single-flight', async () => {
  const [adapter, outlineSchema, outbox, config, compose] = await Promise.all([
    read('../src/openai-compatible-agent-work-adapter.mjs'),
    read('../src/course-outline-schema.mjs'),
    read('../src/outbox.mjs'),
    read('../src/config.mjs'),
    read('../compose.yaml'),
  ]);
  assert.match(outlineSchema, /maxLength/u);
  assert.match(adapter, /deliveryStaleSeconds/u);
  assert.match(adapter, /RETURNING state, result/u);
  assert.match(adapter, /course inference delivery is already in progress/u);
  assert.match(outbox, /this\.userDrains = new Map\(\)/u);
  assert.match(outbox, /this\.drainUserOnce\(userId\)/u);
  assert.match(config, /'OUTBOX_PROCESSING_STALE_SECONDS',\s*240/u);
  assert.match(compose, /COURSE_OUTBOX_PROCESSING_STALE_SECONDS:-240/u);
});
